// Command bench is whittle's reproducible benchmark harness: it runs the checked-in
// corpus through the engine and verifies ROUTING, ACTION, and REDUCTION against
// baseline.json — plus fixture byte-integrity (SHA-256), so the numbers in
// REPORT.md are regenerable, honest artifacts. CI fails on any drift.
//
//	go run ./bench            # verify against baseline
//	go run ./bench -update    # regenerate baseline + REPORT.md
package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/firstops-dev/whittle"
	"github.com/firstops-dev/whittle/compress"
)

type row struct {
	File      string  `json:"file"`
	SHA       string  `json:"sha"`
	Detected  string  `json:"detected"`
	Action    string  `json:"action"`
	Skip      string  `json:"skip_reason,omitempty"`
	Strategy  string  `json:"strategy,omitempty"`
	Reduction float64 `json:"token_reduction"` // estimated-token basis, labeled in REPORT
}

func main() {
	update := flag.Bool("update", false, "regenerate baseline + REPORT.md")
	flag.Parse()

	eng := whittle.New(whittle.Options{ModelURL: os.Getenv("WHITTLE_MODEL_URL"), MinTokens: 0})
	var rows []row
	root := "bench/corpus"
	_ = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || strings.HasSuffix(p, "LICENSES.md") {
			return err
		}
		b, err := os.ReadFile(p) // raw bytes — never newline-translated
		if err != nil {
			return err
		}
		sum := sha256.Sum256(b)
		out := eng.CompressInput(context.Background(), compress.Input{Content: string(b), MinTokens: 0})
		in, o := compress.EstimateTokens(string(b)), compress.EstimateTokens(out.Output)
		red := 0.0
		if in > 0 {
			red = float64(in-o) / float64(in)
		}
		rows = append(rows, row{
			File: strings.TrimPrefix(p, root+"/"), SHA: hex.EncodeToString(sum[:6]),
			Detected: string(out.Detected), Action: out.Action, Skip: out.SkipReason,
			Strategy: out.Strategy, Reduction: float64(int(red*1000)) / 1000,
		})
		return nil
	})
	sort.Slice(rows, func(a, b int) bool { return rows[a].File < rows[b].File })

	if *update {
		bl, _ := json.MarshalIndent(rows, "", " ")
		must(os.WriteFile("bench/baseline.json", bl, 0o644))
		writeReport(rows)
		fmt.Printf("bench: baseline + REPORT regenerated (%d files)\n", len(rows))
		return
	}

	var base []row
	bb, err := os.ReadFile("bench/baseline.json")
	must(err)
	must(json.Unmarshal(bb, &base))
	baseBy := map[string]row{}
	for _, r := range base {
		baseBy[r.File] = r
	}
	fails := 0
	for _, r := range rows {
		b, ok := baseBy[r.File]
		switch {
		case !ok:
			fmt.Printf("FAIL %s: not in baseline (run -update)\n", r.File)
		case r.SHA != b.SHA:
			fmt.Printf("FAIL %s: fixture bytes changed on disk (SHA drift)\n", r.File)
		case r.Detected != b.Detected || r.Action != b.Action:
			fmt.Printf("FAIL %s: routing drift: %s/%s want %s/%s\n", r.File, r.Detected, r.Action, b.Detected, b.Action)
		case r.Reduction < b.Reduction-0.02:
			fmt.Printf("FAIL %s: reduction regressed: %.3f < %.3f\n", r.File, r.Reduction, b.Reduction)
		default:
			continue
		}
		fails++
	}
	if fails > 0 {
		fmt.Printf("bench: %d failure(s)\n", fails)
		os.Exit(1)
	}
	fmt.Printf("bench: %d files verified against baseline\n", len(rows))
}

func writeReport(rows []row) {
	var b strings.Builder
	b.WriteString("# whittle benchmark report\n\nGenerated by `go run ./bench -update`. Reductions are ESTIMATED tokens\n(calibrated vs o200k, MAE ~8%); `skipped` rows are the safety contract working\n(code/config must never be compressed; prose above the latency ceiling passes\nthrough). ML prose rows require the sidecar (`WHITTLE_MODEL_URL`).\n\n| file | detected | action | strategy | token reduction |\n|---|---|---|---|---|\n")
	for _, r := range rows {
		act := r.Action
		if r.Skip != "" {
			act += " (" + r.Skip + ")"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %.1f%% |\n", r.File, r.Detected, act, r.Strategy, r.Reduction*100)
	}
	must(os.WriteFile("bench/REPORT.md", []byte(b.String()), 0o644))
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "bench:", err)
		os.Exit(1)
	}
}
